export const USER_AUTH_REQUEST = "USER_AUTH_REQUEST";
export const USER_AUTH_SUCCESS = "USER_AUTH_SUCCESS";
export const USER_AUTH_ERROR = "USER_AUTH_ERROR";

export const USER_ACTION_REQUEST = "USER_ACTION_REQUEST";
export const ADD_MESSAGE_ERROR = "ADD_MESSAGE_ERROR";

export const GET_FRIENDS_SUCCESS = "GET_FRIENDS_SUCCESS";
export const GET_FRIENDS_ERROR = "GET_FRIENDS_ERROR";

export const GET_MESSAGES_SUCCESS = "GET_MESSAGES_SUCCESS";
export const GET_MESSAGES_ERROR = "GET_MESSAGES_ERROR";

export const GET_FRIEND_INFO_SUCCESS = "GET_FRIEND_INFO_SUCCESS";
export const GET_FRIEND_INFO_ERROR = "GET_FRIEND_INFO_ERROR";


export const GET_POSTS_SUCCESS = "GET_POSTS_SUCCESS";
export const GET_POSTS_ERROR = "GET_POSTS_ERROR";
export const ADD_POST_ERROR = "ADD_POST_ERROR";
 

